# Generated by Django 5.2.9 on 2026-01-03 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userName",
                    models.TextField(blank=True, null=True, verbose_name="用户名"),
                ),
                (
                    "fansCount",
                    models.TextField(blank=True, null=True, verbose_name="粉丝数"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="视频描述"),
                ),
                (
                    "awemeId",
                    models.TextField(blank=True, null=True, verbose_name="视频ID"),
                ),
                (
                    "publishTime",
                    models.TextField(blank=True, null=True, verbose_name="发布时间"),
                ),
                (
                    "duration",
                    models.TextField(blank=True, null=True, verbose_name="视频时长"),
                ),
                (
                    "commentCount",
                    models.TextField(blank=True, null=True, verbose_name="评论数"),
                ),
                (
                    "likeCount",
                    models.TextField(blank=True, null=True, verbose_name="点赞数"),
                ),
                (
                    "shareCount",
                    models.TextField(blank=True, null=True, verbose_name="分享数"),
                ),
                (
                    "collectCount",
                    models.TextField(blank=True, null=True, verbose_name="收藏数"),
                ),
            ],
            options={
                "verbose_name": "视频信息",
                "db_table": "video_data",
            },
        ),
    ]
