# Generated by Django 5.2.9 on 2026-01-03 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videodata",
            name="collectCount",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="收藏数"),
        ),
        migrations.AlterField(
            model_name="videodata",
            name="fansCount",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="粉丝数"),
        ),
        migrations.AlterField(
            model_name="videodata",
            name="likeCount",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="点赞数"),
        ),
        migrations.AlterField(
            model_name="videodata",
            name="shareCount",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="分享数"),
        ),
    ]
