# Generated by Django 5.2.9 on 2026-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0002_alter_videodata_collectcount_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "userId",
                    models.BigIntegerField(blank=True, null=True, verbose_name="用户ID"),
                ),
                (
                    "userName",
                    models.TextField(blank=True, null=True, verbose_name="用户名"),
                ),
                (
                    "commentTime",
                    models.TextField(blank=True, null=True, verbose_name="评论时间"),
                ),
                (
                    "userIP",
                    models.TextField(blank=True, null=True, verbose_name="用户IP"),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="评论内容"),
                ),
                (
                    "likeCount",
                    models.BigIntegerField(blank=True, null=True, verbose_name="点赞数"),
                ),
                (
                    "awemeId",
                    models.BigIntegerField(blank=True, null=True, verbose_name="视频ID"),
                ),
            ],
            options={
                "verbose_name": "评论信息",
                "db_table": "commen_data",
            },
        ),
    ]
